# Generated by Django 4.1 on 2023-01-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='shopadd',
            field=models.TextField(max_length=300),
        ),
    ]
