# Generated by Django 4.1 on 2023-01-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_vender_shopadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='shopcno',
            field=models.CharField(max_length=100),
        ),
    ]
