# Generated by Django 4.1 on 2023-01-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_vender_shopcno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vender',
            old_name='regno',
            new_name='regno_userno',
        ),
    ]
