# Generated by Django 4.1 on 2023-01-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_rename_regno_vender_regno_userno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAdd',
            new_name='Product',
        ),
    ]
