# Generated by Django 4.1 on 2023-01-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_delete_product_alter_vender_regno_userno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vender',
            old_name='regno_userno',
            new_name='registration_no',
        ),
    ]
