# Generated by Django 4.1 on 2022-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category_admin_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_registration',
            name='admin_user',
            field=models.CharField(max_length=100),
        ),
    ]
