# Generated by Django 4.1 on 2023-01-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_admin_registration_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Registration',
        ),
    ]
